Repository openshift/metallb-operator, pull requests merged in 2021-11, with the labels that each got.

#41 Bug 2021053: Update provider and source repo in d/s manifests to Red Hat
  manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml
  manifests/4.9/metallb-operator.v4.9.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#42 Bug 2023212: Update provider and source repo in d/s manifests to Red Hat
  manifests/4.9/metallb-operator.v4.9.0.clusterserviceversion.yaml
Labels: cherry-pick-approved, approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, backport-risk-assessed

#46 Set FRR mode as the default METALLB_BGP_TYPE
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  config/manager/env.yaml
Labels: approved, lgtm

#44 Change the frr image to the openshift one
  manifests/4.10/image-references
  manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml
Labels: approved, lgtm
