Repository openshift/metallb-operator, pull requests merged in 2021-08, with the labels that each got.

#27 Bug 1987136: Declare supported arches in CSV
  manifests/4.9/metallb-operator.v4.9.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#28 Bug 1991316: Update MetalLB CSV namespace to start with openshift prefix
  manifests/4.9/metallb-operator.v4.9.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#29 Bug 1994979: Fix olm.skipRange replacements
  manifests/4.9/metallb-operator.v4.9.0.clusterserviceversion.yaml
  manifests/art.yaml
Labels: bugzilla/severity-high, approved, bugzilla/valid-bug, lgtm
