Repository openshift/metallb-operator, pull requests merged in 2022-01, with the labels that each got.

#51 Bug 2034410: D/S only: Deploy ServiceMonitors
  .github/workflows/general.yml
  bindata/deployment/frr/metallb-frr.yaml
  bindata/deployment/frr/service-monitors.yaml
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  config/manager/env.yaml
  config/metallb_rbac/kube_rbac_proxy.yaml
  config/metallb_rbac/kustomization.yaml
  controllers/metallb_controller.go
  controllers/metallb_controller_test.go
  hack/generate-metallb-manifests.sh
  hack/kube-rbac-controller.json
  hack/kube-rbac-frr.json
  hack/kube-rbac-speaker.json
  manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml
  manifests/4.10/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  manifests/4.10/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#53 Bug 2041483: Add kube-rbac-proxy to image refs
  manifests/4.10/image-references
Labels: bugzilla/severity-high, approved, bugzilla/valid-bug, lgtm

#54 Bug 2041087: MetalLB CR yaml was enforcing nodeSelector which is an optional config
  manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#56 Bug 2041087: sync with u/s metallb-operator
  .github/workflows/general.yml
  .github/workflows/metallb_e2e.yml
  Makefile
  README.md
  bin/metallb-operator-with-webhooks.yaml
  bin/metallb-operator.yaml
  bindata/deployment/frr/metallb-frr.yaml
  bindata/deployment/frr/service-monitors.yaml
  bindata/deployment/native/metallb.yaml
  bindata/deployment/prometheus-operator/prometheus-operator.yaml
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  controllers/metallb_controller.go
  hack/generate-metallb-manifests.sh
  test/e2e/functional/tests/e2e.go
  test/e2e/metallb/metallb.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, qe-approved

#57 Bug 2043234: In FRR mode its not possible to have duplicate BGPPeers
  api/v1beta1/bgppeer_webhook.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
