Repository openshift/metallb-operator, pull requests merged in 2022-09, with the labels that each got.

#111 Bug 2100845: Enable webhook for l2advertisement
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#113 OCPBUGS-757: Extend the max asn number to match 4 bytes
  Makefile
  api/v1beta1/bgppeer_types.go
  bin/metallb-operator-with-webhooks.yaml
  bin/metallb-operator.yaml
  bundle/manifests/metallb.io_bgppeers.yaml
  config/crd/bases/metallb.io_bgppeers.yaml
  manifests/4.10/metallb.io_bgppeers.yaml
Labels: cherry-pick-approved, approved, bugzilla/valid-bug, lgtm, backport-risk-assessed, jira/valid-bug

#117 Validating webhook for bfdprofile on create
  manifests/4.11/metallb-operator.v4.11.0.clusterserviceversion.yaml
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#118 Sync 090922
  .github/workflows/cancel.yaml
  .github/workflows/general.yml
  .github/workflows/go.yml
  .github/workflows/metallb_e2e.yml
  .github/workflows/olm.yml
  .github/workflows/publish.yaml
  .github/workflows/upgrade.yml
  CODEOWNERS
  Dockerfile
  Makefile
  bin/metallb-operator.yaml
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  bundle/manifests/metallb.io_l2advertisements.yaml
  config/crd/bases/metallb.io_l2advertisements.yaml
  config/manager/kustomization.yaml
  config/olm-install/install-resources.yaml
  config/samples/demo/metallb-advanced-config.yaml
  go.mod
  hack/bump_versions.sh
  hack/common.sh
  hack/create_second_interface.sh
  hack/operator_version.txt
  manifests/stable/metallb.io_l2advertisements.yaml
Labels: approved, lgtm

#119 Add openshift labels to the bundle dockerfile
  bundle.Dockerfile
Labels: approved, lgtm

#115 Enable l2adv webhook for 4.11 manifest
  manifests/4.11/metallb-operator.v4.11.0.clusterserviceversion.yaml
Labels: approved, lgtm
