Repository openshift/metallb-operator, pull requests merged in 2022-02, with the labels that each got.

#58 Bug 2048219: AddressPool validation webhook: Add BGPAdvertisements validation
  api/v1beta1/addresspool_webhook.go
  api/v1beta1/addresspool_webhook_test.go
  test/e2e/functional/tests/e2e.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#61 Bug 2050869: MetalLB CR: add speaker pods Tolerations support
  api/v1beta1/metallb_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bin/metallb-operator-with-webhooks.yaml
  bin/metallb-operator.yaml
  bundle/manifests/metallb.io_metallbs.yaml
  config/crd/bases/metallb.io_metallbs.yaml
  config/samples/demo/metallb.yaml
  controllers/metallb_controller.go
  controllers/metallb_controller_test.go
  manifests/4.10/metallb.io_metallbs.yaml
Labels: bugzilla/severity-high, approved, bugzilla/valid-bug, lgtm

#62 Bug 2051722: Add ebgpMultihop to OCP 4.10 manifest
  manifests/4.10/metallb.io_bgppeers.yaml
Labels: bugzilla/severity-high, approved, bugzilla/valid-bug, lgtm

#67 [release-4.9] Bug 2052549: backport MetalLB CR nodeSelector and Tolerations support to 4.9
  api/v1beta1/metallb_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/metallb.io_metallbs.yaml
  config/crd/bases/metallb.io_metallbs.yaml
  controllers/metallb_controller.go
  controllers/metallb_controller_test.go
  manifests/4.9/metallb.io_metallbs.yaml
Labels: cherry-pick-approved, bugzilla/severity-high, approved, staff-eng-approved, bugzilla/valid-bug, lgtm, backport-risk-assessed

#69 Bug 2051718: Add holdtime webhook validation
  api/v1beta1/bgppeer_webhook.go
  api/v1beta1/bgppeer_webhook_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
