Repository openshift/metallb-operator, pull requests merged in 2023-06, with the labels that each got.

#163 OCPBUGS-14410: Add permissions to the speaker to read configmaps
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#157 OCPBUGS-10817: Change the csv version to 4.14
  bundle.Dockerfile
  manifests/metallb-operator.package.yaml
  manifests/ocpcsv/align.sh
  manifests/ocpcsv/bases/metallb-operator.clusterserviceversion.yaml
  manifests/ocpcsv/controller-webhook-patch.yaml
  manifests/ocpcsv/ocpvariables.yaml
  manifests/stable/image-references
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#165 OCPBUGS-14277: Fix ml_secret volumeMount location
  bindata/deployment/openshift/metallb-openshift.yaml
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#167 OCPBUGS-11824: Add the "support disconnected" infrastructure annotation
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#169 OCPBUGS-14830: Remove the service account from the bundle as it's alredy in csv
  bundle/manifests/manager-account_v1_serviceaccount.yaml
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#170 OCPBUGS-14830: Remove the service account file from manifests/stable
  manifests/stable/manager-account_v1_serviceaccount.yaml
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#166 Align with upstream 07-06-2023
  .github/workflows/bump_metallb.yml
  .github/workflows/metallb_e2e.yml
  .gitignore
  Makefile
  api/v1beta1/metallb_types.go
  bin/metallb-operator.yaml
  bindata/deployment/helm/templates/speaker.yaml
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  bundle/manifests/metallb.io_bgpadvertisements.yaml
  bundle/manifests/metallb.io_communities.yaml
  bundle/manifests/metallb.io_metallbs.yaml
  config/crd/bases/metallb.io_bgpadvertisements.yaml
  config/crd/bases/metallb.io_communities.yaml
  config/crd/bases/metallb.io_metallbs.yaml
  config/samples/demo/metallb-advanced-config.yaml
  config/samples/demo/metallb.yaml
  controllers/metallb_controller.go
  hack/bump_metallb.sh
  hack/common.sh
  hack/generate-metallb-manifests.sh
  hack/metallb_ref.txt
  pkg/helm/config.go
  pkg/helm/helm_test.go
  pkg/helm/testdata/ocp-metrics-speaker.golden
  pkg/helm/testdata/vanilla-metrics-speaker.golden
  test/e2e/functional/tests/e2e.go
  test/e2e/metallb/metallb.go
Labels: approved, lgtm

#164 OCPBUGS-14503: [4.10] Change the memberlist secret to contain path
  bindata/deployment/frr/metallb-frr.yaml
  bindata/deployment/native/metallb.yaml
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#173 OCPBUGS-8433: [4.13] Fix metallb controller error log
  controllers/metallb_controller.go
  test/e2e/functional/tests/e2e.go
  test/e2e/metallb/metallb.go
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#175 [release-4.11] OCPBUGS-15567: Fix metallb controller error log
  controllers/metallb_controller.go
  test/e2e/functional/tests/e2e.go
  test/e2e/metallb/metallb.go
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
