Repository openshift/metallb-operator, pull requests merged in 2023-03, with the labels that each got.

#139 OCPBUGS-8019: Read the memberlist secret from a file
  bindata/deployment/helm/README.md
  bindata/deployment/helm/policy/speaker.rego
  bindata/deployment/helm/templates/speaker.yaml
  bindata/deployment/helm/values.schema.json
  bindata/deployment/helm/values.yaml
  hack/common.sh
  pkg/helm/testdata/ocp-metrics-speaker.golden
  pkg/helm/testdata/ocp-speaker.golden
  pkg/helm/testdata/vanilla-metrics-speaker.golden
Labels: cherry-pick-approved, approved, bugzilla/valid-bug, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#141 OCPBUGS-10024: Controller metrics: set the rbac proxy upstream to localhost
  bindata/deployment/openshift/metallb-openshift.yaml
Labels: cherry-pick-approved, approved, bugzilla/valid-bug, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#132 Add the "support disconnected" infrastructure annotation
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#147 Align with upstream 28-03-2023
  .github/workflows/general.yml
  .github/workflows/metallb_e2e.yml
  .github/workflows/olm.yml
  .github/workflows/publish.yaml
  Makefile
  README.md
  bin/metallb-operator.yaml
  bindata/deployment/helm/README.md
  bindata/deployment/helm/templates/controller.yaml
  bindata/deployment/helm/templates/exclude-l2-config.yaml
  bindata/deployment/helm/templates/servicemonitor.yaml
  bindata/deployment/helm/templates/speaker.yaml
  bindata/deployment/helm/values.schema.json
  bindata/deployment/helm/values.yaml
  bundle.Dockerfile
  bundle/manifests/controller_v1_serviceaccount.yaml
  bundle/manifests/manager-account_v1_serviceaccount.yaml
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  bundle/manifests/metallb.io_addresspools.yaml
  bundle/manifests/metallb.io_bfdprofiles.yaml
  bundle/manifests/metallb.io_bgpadvertisements.yaml
  bundle/manifests/metallb.io_bgppeers.yaml
  bundle/manifests/metallb.io_communities.yaml
  bundle/manifests/metallb.io_ipaddresspools.yaml
  bundle/manifests/metallb.io_l2advertisements.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/metallb.io_addresspools.yaml
  config/crd/bases/metallb.io_bfdprofiles.yaml
  config/crd/bases/metallb.io_bgpadvertisements.yaml
  config/crd/bases/metallb.io_bgppeers.yaml
  config/crd/bases/metallb.io_communities.yaml
  config/crd/bases/metallb.io_ipaddresspools.yaml
  config/crd/bases/metallb.io_l2advertisements.yaml
  config/manager/env.yaml
  config/manifests/bases/metallb-operator.clusterserviceversion.yaml
  config/metallb_rbac/metallb-frr.yaml
  config/metallb_rbac/metallb-native.yaml
  config/metallb_rbac/metallb-openshift.yaml
  config/openshift/custom-namespace-transformer.yaml
  config/openshift/kustomization.yaml
  config/openshift/patch-deployment-controller-manager.yaml
  config/openshift/patch-namespace.yaml
  config/openshift/privileged-role-binding.yaml
  config/webhook/webhook/manifests.yaml
  hack/common.sh
  pkg/helm/helm_test.go
  pkg/helm/testdata/ocp-metrics-controller.golden
  pkg/helm/testdata/ocp-metrics-speaker.golden
  pkg/helm/testdata/vanilla-metrics-speaker.golden
  test/e2e/k8sreporter/reporter.go
  test/e2e/namespaces/namespaces.go
Labels: approved, lgtm
