Repository openshift/metallb-operator, pull requests merged in 2023-04, with the labels that each got.

#154 OCPBUGS-11443: Controller metrics port: fix typo
  bindata/deployment/openshift/metallb-openshift.yaml
Labels: cherry-pick-approved, approved, bugzilla/valid-bug, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#153 Openshift only: generate and enforce the csv
  manifests/ocpcsv/align.sh
  manifests/ocpcsv/bases/metallb-manager-role_rbac.authorization.k8s.io_v1_role.yaml
  manifests/ocpcsv/bases/metallb-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/ocpcsv/bases/metallb-operator.clusterserviceversion.yaml
  manifests/ocpcsv/bases/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  manifests/ocpcsv/bases/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/ocpcsv/controller-webhook-patch.yaml
  manifests/ocpcsv/disable-cert-rotation.yaml
  manifests/ocpcsv/kustomization.yaml
  manifests/ocpcsv/ocpvariables.yaml
  manifests/ocpcsv/permission-patch.yaml
  manifests/ocpcsv/verify.sh
  manifests/ocpcsv/webhookservicecainjection_patch.yaml
  manifests/stable/manager-account_v1_serviceaccount.yaml
  manifests/stable/metallb-operator.clusterserviceversion.yaml
  manifests/stable/metallb.io_addresspools.yaml
  manifests/stable/metallb.io_bfdprofiles.yaml
  manifests/stable/metallb.io_bgpadvertisements.yaml
  manifests/stable/metallb.io_bgppeers.yaml
  manifests/stable/metallb.io_communities.yaml
  manifests/stable/metallb.io_ipaddresspools.yaml
  manifests/stable/metallb.io_l2advertisements.yaml
  manifests/stable/metallb.io_metallbs.yaml
  manifests/stable/webhook-service_v1_service.yaml
Labels: approved, lgtm

#155 OCPBUGS-11861: Configure speaker and controller --log-level
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/metallb_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bin/metallb-operator-with-webhooks.yaml
  bin/metallb-operator.yaml
  bindata/deployment/frr/metallb-frr.yaml
  bindata/deployment/native/metallb.yaml
  bundle/manifests/metallb.io_metallbs.yaml
  config/crd/bases/metallb.io_metallbs.yaml
  controllers/metallb_controller.go
  controllers/metallb_controller_test.go
  controllers/suite_test.go
  hack/generate-metallb-manifests.sh
Labels: cherry-pick-approved, approved, bugzilla/valid-bug, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
