Repository openshift/metallb-operator, pull requests merged in 2023-08, with the labels that each got.

#181 Add Ori to OWNERS
  OWNERS
Labels: approved, lgtm

#180 OCPBUGS-17122: Fix conversion webhook
  manifests/stable/metallb-operator.clusterserviceversion.yaml
  manifests/stable/metallb.io_addresspools.yaml
  manifests/stable/metallb.io_bgppeers.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#178 OCPBUGS-15454: Fix flake MetalLB resources should have correct statuses
  controllers/metallb_controller.go
  hack/kind-cluster-with-registry.sh
  hack/kind-cluster-without-registry.sh
  hack/kind-multi-node-cluster-without-registry.sh
  pkg/status/status.go
  test/e2e/functional/tests/e2e.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#182 [release-4.13] OCPBUGS-8433: Fix flake MetalLB resources should have correct statuses
  controllers/metallb_controller.go
  pkg/status/status.go
  test/e2e/functional/tests/e2e.go
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#183 [release-4.12] OCPBUGS-15771: Fix flake MetalLB resources should have correct statuses
  controllers/metallb_controller.go
  pkg/status/status.go
  test/e2e/functional/tests/e2e.go
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
