Repository openshift/metallb-operator, pull requests merged in 2023-01, with the labels that each got.

#130 OCPBUGS-5394: Fix invalid verification error when using aggregationLengthV6 only
  api/v1beta1/addresspool_webhook.go
Labels: cherry-pick-approved, approved, bugzilla/valid-bug, lgtm, backport-risk-assessed, jira/severity-critical, jira/valid-bug

#129 Align with upstream 22-12-22
  .github/workflows/metallb_e2e.yml
  .github/workflows/upgrade.yml
  bin/metallb-operator.yaml
  bindata/deployment/helm/README.md
  bindata/deployment/helm/templates/podmonitor.yaml
  bindata/deployment/helm/templates/servicemonitor.yaml
  bindata/deployment/helm/templates/speaker.yaml
  bindata/deployment/helm/values.schema.json
  bindata/deployment/helm/values.yaml
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  bundle/manifests/metallb.io_bfdprofiles.yaml
  bundle/manifests/metallb.io_bgpadvertisements.yaml
  bundle/manifests/metallb.io_bgppeers.yaml
  bundle/manifests/metallb.io_ipaddresspools.yaml
  bundle/manifests/metallb.io_l2advertisements.yaml
  config/crd/bases/metallb.io_bfdprofiles.yaml
  config/crd/bases/metallb.io_bgpadvertisements.yaml
  config/crd/bases/metallb.io_bgppeers.yaml
  config/crd/bases/metallb.io_ipaddresspools.yaml
  config/crd/bases/metallb.io_l2advertisements.yaml
  config/manager/manager.yaml
  config/metallb_rbac/metallb-frr.yaml
  config/metallb_rbac/metallb-native.yaml
  config/metallb_rbac/metallb-openshift.yaml
  controllers/metallb_controller.go
  controllers/metallb_controller_test.go
  hack/bump_versions.sh
  hack/common.sh
  main.go
  manifests/stable/metallb.io_bfdprofiles.yaml
  manifests/stable/metallb.io_bgpadvertisements.yaml
  manifests/stable/metallb.io_bgppeers.yaml
  manifests/stable/metallb.io_ipaddresspools.yaml
  manifests/stable/metallb.io_l2advertisements.yaml
  pkg/helm/testdata/ocp-metrics-speaker.golden
  pkg/helm/testdata/vanilla-metrics-speaker.golden
  test/e2e/functional/tests/e2e.go
  test/e2e/validation/tests/validation.go
Labels: approved, lgtm

#134 OCPBUGS-6033: Helm: propagate the rbac image values to the charts
  pkg/helm/config.go
  pkg/helm/helm_test.go
  pkg/helm/testdata/vanilla-metrics-speaker.golden
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#128 OCPBUGS-4447: Bump up the version
  .ci-operator.yaml
  Dockerfile.openshift
  bundle.Dockerfile
  manifests/metallb-operator.package.yaml
  manifests/stable/image-references
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference
