Repository openshift/metallb-operator, pull requests merged in 2024-10, with the labels that each got.

#243 Syncmetallboperator031024
  pkg/helm/frrk8s.go
  pkg/helm/frrk8s_test.go
Labels: approved, lgtm

#244 Align to upstream, including CRDs
  .github/workflows/bump_metallb.yml
  .github/workflows/ci.yaml
  .github/workflows/composite/collectlogs/action.yaml
  .github/workflows/composite/setup/action.yaml
  .github/workflows/publish.yaml
  .github/workflows/verify_version.yaml
  bin/metallb-operator.yaml
  bindata/deployment/helm/frr-k8s/Chart.lock
  bindata/deployment/helm/frr-k8s/Chart.yaml
  bindata/deployment/helm/frr-k8s/README.md
  bindata/deployment/helm/metallb/Chart.lock
  bindata/deployment/helm/metallb/README.md
  bindata/deployment/helm/metallb/templates/controller.yaml
  bindata/deployment/helm/metallb/templates/podmonitor.yaml
  bindata/deployment/helm/metallb/templates/servicemonitor.yaml
  bindata/deployment/helm/metallb/values.yaml
  bundle/manifests/frrk8s.metallb.io_frrconfigurations.yaml
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  bundle/manifests/metallb.io_bfdprofiles.yaml
  bundle/manifests/metallb.io_bgpadvertisements.yaml
  bundle/manifests/metallb.io_bgppeers.yaml
  bundle/manifests/metallb.io_communities.yaml
  bundle/manifests/metallb.io_ipaddresspools.yaml
  bundle/manifests/metallb.io_l2advertisements.yaml
  bundle/manifests/metallb.io_servicel2statuses.yaml
  config/crd/bases/frrk8s.metallb.io_frrconfigurations.yaml
  config/crd/bases/metallb.io_bfdprofiles.yaml
  config/crd/bases/metallb.io_bgpadvertisements.yaml
  config/crd/bases/metallb.io_bgppeers.yaml
  config/crd/bases/metallb.io_communities.yaml
  config/crd/bases/metallb.io_ipaddresspools.yaml
  config/crd/bases/metallb.io_l2advertisements.yaml
  config/crd/bases/metallb.io_servicel2statuses.yaml
  config/manager/env.yaml
  config/metallb_rbac/metallb.yaml
  hack/metallb_ref.txt
  manifests/stable/frrk8s.metallb.io_frrconfigurations.yaml
  manifests/stable/frrk8s.metallb.io_frrnodestates.yaml
  manifests/stable/metallb-operator.clusterserviceversion.yaml
  manifests/stable/metallb.io_bfdprofiles.yaml
  manifests/stable/metallb.io_bgpadvertisements.yaml
  manifests/stable/metallb.io_bgppeers.yaml
  manifests/stable/metallb.io_communities.yaml
  manifests/stable/metallb.io_ipaddresspools.yaml
  manifests/stable/metallb.io_l2advertisements.yaml
  manifests/stable/metallb.io_servicel2statuses.yaml
  pkg/helm/testdata/ocp-metrics-controller-monitor.golden
  pkg/helm/testdata/ocp-metrics-frr-k8s-daemon.golden
  pkg/helm/testdata/ocp-metrics-frr-k8s-monitor.golden
  pkg/helm/testdata/ocp-metrics-frr-k8s-webhook.golden
  pkg/helm/testdata/vanilla-metrics-controller-monitor.golden
Labels: approved, lgtm

#246 OCPBUGS-41937: Align the versions to 4.18
  bundle.Dockerfile
  manifests/metallb-operator.package.yaml
  manifests/ocpcsv/align.sh
  manifests/ocpcsv/bases/metallb-operator.clusterserviceversion.yaml
  manifests/ocpcsv/controller-webhook-patch.yaml
  manifests/ocpcsv/ocpvariables.yaml
  manifests/stable/image-references
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#245 OCPBUGS-39540: Align upstream + delete permission on frr configuration
  bin/metallb-operator.yaml
  bindata/deployment/helm/metallb/README.md
  bindata/deployment/helm/metallb/templates/prometheusrules.yaml
  bindata/deployment/helm/metallb/values.yaml
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  bundle/manifests/metallb.io_bgppeers.yaml
  config/crd/bases/metallb.io_bgppeers.yaml
  hack/metallb_ref.txt
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#241 [release-4.16] OCPBUGS-41805: set required-scc for openshift workloads
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#247 OpenShift: align CRDs
  manifests/stable/metallb.io_bgppeers.yaml
Labels: approved, lgtm
