Repository openshift/metallb-operator, pull requests merged in 2025-02, with the labels that each got.

#254 Align upstream: 27-1-2025
  .github/workflows/ci.yaml
  .github/workflows/publish.yaml
  controllers/metallb_controller.go
  go.mod
  go.sum
  hack/ocp_run_e2e.sh
  manifests/stable/metallb-operator.clusterserviceversion.yaml
  pkg/openshift/openshift.go
  pkg/openshift/openshift_test.go
  pkg/params/params.go
  test/e2e/functional/tests/e2e.go
  vendor/github.com/Masterminds/semver/.travis.yml
  vendor/github.com/Masterminds/semver/CHANGELOG.md
  vendor/github.com/Masterminds/semver/LICENSE.txt
  vendor/github.com/Masterminds/semver/Makefile
  vendor/github.com/Masterminds/semver/README.md
  vendor/github.com/Masterminds/semver/appveyor.yml
  vendor/github.com/Masterminds/semver/collection.go
  vendor/github.com/Masterminds/semver/constraints.go
  vendor/github.com/Masterminds/semver/doc.go
  vendor/github.com/Masterminds/semver/version.go
  vendor/github.com/Masterminds/semver/version_fuzz.go
  vendor/modules.txt
Labels: approved, lgtm

#257 NO-JIRA: Fix 4.19 CSV references
  manifests/stable/metallb-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#252 OCPBUGS-48305: Bump the frr-k8s manifests to use the metrics port for healtchecks
  bin/metallb-operator.yaml
  bindata/deployment/helm/frr-k8s/Chart.lock
  bindata/deployment/helm/frr-k8s/Chart.yaml
  bindata/deployment/helm/frr-k8s/README.md
  bindata/deployment/helm/frr-k8s/templates/controller.yaml
  bindata/deployment/helm/frr-k8s/templates/webhooks.yaml
  bindata/deployment/helm/frr-k8s/values.yaml
  bindata/deployment/helm/metallb/Chart.lock
  bindata/deployment/helm/metallb/README.md
  bundle/manifests/metallb-operator.clusterserviceversion.yaml
  bundle/manifests/metallb.io_bgppeers.yaml
  config/crd/bases/metallb.io_bgppeers.yaml
  config/manager/env.yaml
  hack/metallb_ref.txt
  pkg/helm/testdata/ocp-metrics-frr-k8s-daemon.golden
  pkg/helm/testdata/ocp-metrics-frr-k8s-monitor.golden
  pkg/helm/testdata/ocp-metrics-frr-k8s-webhook.golden
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
